version: "2"

services:
  voting-app:
    image: nicolaka/voting-app:latest
    ports:
      - "80"
    networks:
      voteapp:
    labels:
     interlock.hostname: "vote"
     interlock.domain:   "example.org"
  result-app:
    image: nicolaka/result-app:latest
    ports:
      - "80"
    networks:
      voteapp:
    labels:
     interlock.hostname: "result"
     interlock.domain:   "example.org"
  worker:
    image: nicolaka/worker:latest
    networks:
      voteapp:
       aliases:
        - workers
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      voteapp:
    container_name: redis

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      voteapp:
    container_name: db
volumes:
  db-data:

networks:
  voteapp:
