version: "2"

services:
  voting-app:
    image: docker/example-voting-app-voting-app
    ports:
      - "80"
    networks:
      - voteapp
    links:
      - redis
  result-app:
    image: docker/example-voting-app-result-app
    ports:
      - "80"
    networks:
      - voteapp
    links:
      - db
  worker:
    image: docker/example-voting-app-worker
    networks:
      - voteapp
    links:
      - db
      - redis
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - voteapp
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - voteapp

volumes:
  db-data:

networks:
  voteapp:
