version: "2"

services:
  voting-app:
    image: trainingteam/voting-app:latest
    ports:
      - "80"
    networks:
      voteapp:
  result-app:
    image: trainingteam/result-app:latest
    ports:
      - "80"
    networks:
      voteapp:
  worker:
    image: trainingteam/worker:latest
    networks:
      voteapp:
       aliases:
        - workers
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      voteapp:
    container_name: redis

  db:
    image: postgres:9.4
    networks:
      voteapp:
    container_name: db

networks:
  voteapp:
