version: "2"

services:
  voting-app:
    image: ehazlett/dockercon-voting-app
    ports:
      - "80:80"
    networks:
      - voteapp
  result-app:
    image: ehazlett/dockercon-result-app
    ports:
      - "5000:80"
    networks:
      - voteapp
  worker:
    image: ehazlett/dockercon-worker
    networks:
      - voteapp
  redis:
    image: redis
    ports:
      - "6379"
    networks:
      - voteapp
    container_name: redis
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - voteapp
    container_name: db
volumes:
  db-data:

networks:
  voteapp:
